[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = ['python']

[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = ['python']
hook_add = '''
'''

[[plugins]]
repo = 'w0rp/ale'
on_ft = ['python']

[[plugins]]
repo = 'Vimjas/vim-python-pep8-indent'
on_ft = ['python']



[[plugins]]
repo = 'othree/yajs'
on_ft = ['javascript']

[[plugins]]
repo = 'zchee/deoplete-zsh'
on_ft = ['sh','bash']
