[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = ['python']

[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = ['python']
hook_add = '''
    let g:deoplete#sources#jedi#python_path = '/Users/rshimura/.pyenv/shims/python'
'''

[[plugins]]
repo = 'w0rp/ale'
on_ft = ['python']

[[plugins]]
repo = 'Vimjas/vim-python-pep8-indent'
on_ft = ['python']

